import { environment } from '../environments/environment';

export const expressapi = {
  sendSignupOTP: environment.apiUrl + '/user/sendSignupOTP',
  signUpOrgAndAdmin: environment.apiUrl + '/user/signUpOrgAndAdmin',
  onLogin: environment.apiUrl + '/user/onLogin',
  getUser: environment.apiUrl + '/user/getUser',
  createProject: environment.apiUrl + '/project/createProject',
  getProjects: environment.apiUrl + '/project/getProjects',
  inviteUser: environment.apiUrl + '/user/inviteUser',
  validateInvitationToken: environment.apiUrl + '/user/validateInvitationToken',
  signUpUser: environment.apiUrl + '/user/signUpUser',
  getUsersByProject: environment.apiUrl + '/user/getUsersByProject',
  createTask: environment.apiUrl + '/task/createTask',
  getTasks: environment.apiUrl + '/task/getTasks',
  getTaskDetails: environment.apiUrl + '/task/getTaskDetails',
  updateTask: environment.apiUrl + '/task/updateTask',
  updateProject: environment.apiUrl + '/project/updateProject',
  getProjectDetails: environment.apiUrl + '/project/getProjectDetails',
  getTasksByStatus: environment.apiUrl + '/task/getTasksByStatus',
  getTasksByProgress: environment.apiUrl + '/task/getTasksByProgress',
  getTasksByPriority: environment.apiUrl + '/task/getTasksByPriority',
  getTasksByMonth: environment.apiUrl + '/task/getTasksByMonth',
  getUserDetails: environment.apiUrl + '/user/getUserDetails',
  changePassword: environment.apiUrl + '/user/changePassword',
  sendForgotPasswordOTP: environment.apiUrl + '/user/sendForgotPasswordOTP',
  submitForgotPassword: environment.apiUrl + '/user/submitForgotPassword',
  getUsersByAdmin: environment.apiUrl + '/user/getUsersByAdmin',
  getUserDetailsForAdmin: environment.apiUrl + '/user/getUserDetailsForAdmin',
  deleteUser: environment.apiUrl + '/user/deleteUser',
  removeFromProject: environment.apiUrl + '/user/removeFromProject',
  generatePdf: environment.apiUrl + '/task/generatePdf',
  projectTasksByStatus: environment.apiUrl + '/project/projectTasksByStatus',
  projectTasksByProgress: environment.apiUrl + '/project/projectTasksByProgress',
  projectTasksByPriority: environment.apiUrl + '/project/projectTasksByPriority',
  groupTasksByAssignedUser: environment.apiUrl + '/project/groupTasksByAssignedUser',
  searchUserByProject: environment.apiUrl + '/user/searchUserByProject',
  addUserToProject: environment.apiUrl + '/project/addUserToProject',
  checkForMultipleOrgs: environment.apiUrl + '/user/checkForMultipleOrgs',
  uploadTasksFromCSV: environment.apiUrl + '/task/uploadTasksFromCSV',
};